---
version: '3.4'
services:
  agent:
    image: orb-agent:develop
    init: true
    ports:
      - 8686:8686
    environment:
      VIZERD_ARGS: eth0 --admin-api
  influxdb:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: dev
      DOCKER_INFLUXDB_INIT_PASSWORD: dev12345
      DOCKER_INFLUXDB_INIT_ORG: dev
      DOCKER_INFLUXDB_INIT_BUCKET: dev
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: seekrit-dev-token
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
volumes:
  influxdb-storage:

